package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "client-main",
    srcs = ["client-main.cc"],
    deps = [
        "//cpp/design-patterns/factories-factory-method/stores:chicago-style-pizza-store",
        "//cpp/design-patterns/factories-factory-method/stores:ny-style-pizza-store",
    ],
)
