package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "pizza-store-main",
    srcs = ["pizza-store-main.cc"],
    deps = [
      "//cpp/design-patterns/decorator/pizzas:farmhouse-pizza",
      "//cpp/design-patterns/decorator/toppings:barbeque",
      "//cpp/design-patterns/decorator/toppings:fresh-tomatoes",
    ],
)