package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "zoo-main",
    srcs = ["zoo-main.cc"],
    deps = [
        "//cpp/design-patterns/strategy/ducks:mallard-duck",
        "//cpp/design-patterns/strategy/ducks:model-duck",
    ],
)