package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pizza",
    hdrs = ["pizza.h"],
)

cc_library(
    name = "farmhouse-pizza",
    hdrs = ["farmhouse-pizza.h"],
    deps = [
        ":pizza"
    ]
)