package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pizza",
    hdrs = ["pizza.h"],
)

cc_library(
    name = "ny-style-cheese-pizza",
    hdrs = ["ny-style-cheese-pizza.h"],
    deps = [
      ":pizza",
    ],
)

cc_library(
    name = "ny-style-veggie-pizza",
    hdrs = ["ny-style-veggie-pizza.h"],
    deps = [
      ":pizza",
    ],
)

cc_library(
    name = "ny-style-clam-pizza",
    hdrs = ["ny-style-clam-pizza.h"],
    deps = [
      ":pizza",
    ],
)

cc_library(
    name = "chicago-style-cheese-pizza",
    hdrs = ["chicago-style-cheese-pizza.h"],
    deps = [
      ":pizza",
    ],
)