package(default_visibility = ["//visibility:public"])

cc_library(
    name = "command",
    hdrs = ["command.h"],
)

cc_library(
    name = "no-command",
    hdrs = ["no-command.h"],
)

cc_library(
    name = "macro-command",
    hdrs = ["macro-command.h"],
)